# Appears in the html tab browser for the site title
title: RekCode

# Disqus comment
disqus:
  shortname: farisfebrianto

# Social media account information, appears on footer
github_username:  farisfebrianto
instagram_username: faris.febrianto

# Site motto, appears on footer
description: "Code to the limit, until you'll know we are limitless"

# Get in touch via email, appears on footer
email: farisfebrianto@outlook.com

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate

# Pagination
paginate: 10
paginate_path: /page:num/

# Show excerpt
show_excerpts: true
excerpt_separator: <!--more-->
